name: 😱 New Feature Request
description: File a special bug/issue
title: "[SEC] <title>"
labels: [Consideration]
body:
- type: markdown
  attributes:
    value: "## Proposing a Feature"
- type: checkboxes
  attributes:
    label: Is there an existing request for this?
    description: Please search to see if the feature is requested
    options:
    - label: I have searched for this feature and don't see a similar request
      required: true
- type: textarea
  attributes:
    label: Requested Behavior
    description: A concise description of what you're requesting. Markdown is supported.
    render: markdown
  validations:
    required: true
- type: dropdown
  id: userType
  attributes:
    label: What type of user will benefit most from this change?
    options:
      - Developer
      - Administrator
      - End-User
      - Data Analyst
  validations:
    required: false
